transparenyc/package-lock.json, transparenyc/package.json
added axios and react router dom
=> added axios and react router dom

transparenyc/src/Components/Categories.js, transparenyc/src/Components/ProjectList.jsx
this is a pull. I have the categories and project list components up.
=> added category and project list page

transparenyc/src/Search.js
File of Search Component.  
As of 3/3, 4:10pm, still need to refine list items.
=> created Search component

transparenyc/src/App.js, transparenyc/src/Components/Categories.js
working on Categories component and rendering agencies
=> working on Categories component and rendering agencies

transparenyc/src/Components/Categories.js, transparenyc/src/Components/SelectList.js
fixed the list of agencies ...sorta
=> fixed the list of agencies ...sorta

transparenyc/src/Search.js
Updated Search Component: 
- neater results/list, added Name, Funds, Project Name, Project Descriptions
- limited results to 10
=> updated Search Component

transparenyc/public/index.html, transparenyc/src/App.css, transparenyc/src/App.js, transparenyc/src/Components/About.js, transparenyc/src/Components/Home.js
added the styling, about page, home page.
=> added the styling and other stuff

transparenyc/package.json, transparenyc/src/App.js, transparenyc/src/Components/Search.js, transparenyc/src/Components/SearchBar.js
Added the search functionality throughout App
=> Logo search

transparenyc/src/App.css, transparenyc/src/App.js, transparenyc/src/Components/Categories.js, transparenyc/src/Components/Contact.js, transparenyc/src/Components/Home.js, transparenyc/src/Components/Search.js, transparenyc/src/Components/SearchBar.js
added the clear search functionality
=> added the clear search functionality

transparenyc/public/index.html, transparenyc/src/App.css, transparenyc/src/Components/SearchBar.js
=> search bar style

transparenyc/src/Components/About.js, transparenyc/src/Components/Search.js
Updated both Search and About Components
=> Search updates

transparenyc/src/App.css, transparenyc/src/App.js, transparenyc/src/Components/Categories.js, transparenyc/src/Components/ProjectList.jsx
=> added the footer

transparenyc/src/App.css
=> added the colors

transparenyc/src/Components/Search.js
=> added a draggable div

transparenyc/src/App.css, transparenyc/src/Components/Home.js
=> added media queries

transparenyc/src/Components/About.js, transparenyc/src/Components/SearchBar.js
Updated icons in Search bar and About Us
=> Updated icons in Search bar and About Us

transparenyc/src/Components/Search.js, transparenyc/src/Components/SearchBar.js
added the fa-fa stuff again I did git push and it messed some stuff up... just except all incoming changes. this is our MVP
=> added the fa-fa stuff again

transparenyc/src/Components/SearchBar.js
rendered the search button disabled if falsy
=> rendered the search button disabled if falsy

transparenyc/src/Components/ProjectList.jsx
Was missing a key to identify funding_source in Line 92.
=> added Funding Source

transparenyc/src/Components/About.js
added target=_blank to github links
=> added target=_blank to github links
